name: release
on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_USERNAME: prnbc
  DOCKER_REPO: prnbc/oitec

jobs:
  build-release:
    name: Release: Tag version with image Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Set environment variables
        run: |
          cat >> $GITHUB_ENV << EOF
          VERSION=${GITHUB_REF##*/}
          EOF

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.event.repository.name }}-latest,${{ env.DOCKER_REPO }}:${{ github.event.repository.name }}-${{ env.VERSION }}
